// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  specV1Sidebar: [{ type: "autogenerated", dirName: "spec-v1" }],
  specExtensionsSidebar: [{ type: "autogenerated", dirName: "spec-extensions" }],
  detailsSidebar: [{ type: "autogenerated", dirName: "details" }],
};

module.exports = sidebars;
